<a href="https://colab.research.google.com/github/seungheekk/Big-Data-Analysis-Programming/blob/main/code/06w_dat6aframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [367]:
# p.32
import pandas as pd

pf = pd.DataFrame(data=[[25,35,8,18],
                        [18,27,10,20],
                        [17, 17, 10, 19],
                        [12, 22, 9,20],
                        [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희','유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])

pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [368]:
pf['과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [369]:
pf.과제

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [370]:
pf[ ['과제'] ]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [371]:
pf.과제

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [372]:
pf[ ['과제', '기말'] ]

     과제  기말
윤일형   8  35
강수희  10  27
홍소희  10  17
유한빈   9  22
신수빈   8  34

In [491]:
import pandas as pd

df = pd.read_csv('2016년졸음운전.csv',encoding='euc-kr',index_col=0)
df

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [374]:
df[['사망(명)', '부상(명)']].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [375]:
df.dtypes

사고(건)    int64
사망(명)    int64
부상(명)    int64
dtype: object

In [376]:
dtype:object

In [489]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2025-03-02 to 2025-03-07
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes

In [492]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [493]:
df.describe()

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [494]:
df2 = df.copy()
df2['재해자수'] = df[['사망(명)', '부상(명)']].sum(axis=1)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368

In [381]:
pf['중간'] >20

윤일형     True
강수희    False
홍소희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [382]:
pf[pf['중간']>20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [383]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [384]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [385]:
import numpy as np
import pandas as pd

s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [386]:
s.name

'first'

In [387]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [388]:
s.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [389]:
s.shape

(6,)

In [390]:
s.size

6

In [391]:
import numpy as np
import pandas as pd


s = pd.Series([1, 3, 5, np.nan, 6, 8], name='first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [392]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [393]:
s[1]

np.float64(3.0)

In [394]:
s[1]

np.float64(3.0)

In [395]:
s.index = list('abcdef')
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [396]:
print(s['b'], s['d'])

3.0 nan

In [397]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

##여러 series로 DataFrame 생성

In [398]:
courses = pd.Series(["Spark","PySpark", "Hadoop"], name='courses')
courses

0      Spark
1    PySpark
2     Hadoop
Name: courses, dtype: object

In [399]:
fees = pd.Series([250000,300000, 200000], name='fees')
fees

0    250000
1    300000
2    200000
Name: fees, dtype: int64

In [400]:
df = pd.DataFrame({courses.name: courses, fees.name:fees})
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [401]:
courses = pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name= 'fees')

df = pd.concat([courses, fees], axis=1)
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [402]:
courses =pd.Series(["Spark", "PySpark", "Hadoop"], name='courses')
fees = pd.Series([250000, 300000, 200000], name='fees')

pf = pd.DataFrame([courses,fees])
df

   courses    fees
0    Spark  250000
1  PySpark  300000
2   Hadoop  200000

In [403]:
df.T

              0        1       2
courses   Spark  PySpark  Hadoop
fees     250000   300000  200000

In [404]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [405]:
courses =pd.Series(["Spark", "Pyspark", "Hadoop"], name='courses')
df[courses.name] = courses
df

   courses
0    Spark
1  Pyspark
2   Hadoop

In [406]:
fees = pd.Series([250000, 300000, 200000], name='fees')
df[fees.name] = fees
df

   courses    fees
0    Spark  250000
1  Pyspark  300000
2   Hadoop  200000

In [407]:
import pandas as pd

df = pd.DataFrame([{'국어':70, '수학': 89, '영어': 90},
                   {'국어': 80, '영어': 99},
                   {'수학': 66, '영어': 78}])
df

     국어    수학  영어
0  70.0  89.0  90
1  80.0   NaN  99
2   NaN  66.0  78

In [408]:
import pandas as pd
s1 = pd.Series([90, 80, 60, 66])
s2 = pd.Series([45, 73, 83, 99])
s3 = pd.Series([92, 75, 82, 75])
s1

0    90
1    80
2    60
3    66
dtype: int64

In [409]:
df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3})
df

   국어  영어  수학
0  90  45  92
1  80  73  75
2  60  83  82
3  66  99  75

In [410]:
df.index = ['노', '장', '박', '강']
df

   국어  영어  수학
노  90  45  92
장  80  73  75
박  60  83  82
강  66  99  75

In [411]:
df = pd.DataFrame({'A': pd.Series([10, 20, 30], index= [0, 1, 2]),
                   'B': pd.Series([3, 2, 1], index=[1, 2, 3])})
df

      A    B
0  10.0  NaN
1  20.0  3.0
2  30.0  2.0
3   NaN  1.0

In [412]:
s1 = pd.Series([90, 80, 60], index=['노', '장', '박'])
s2 = pd.Series([45, 73, 99], index=['장', '박', '강'])
s3 = pd.Series([92, 75, 82, 75])

In [413]:
df = pd.DataFrame({'국어': s1, '영어': s2, '수학': s3},
                  index=['노', '장', '박', '강'])
df

     국어    영어  수학
노  90.0   NaN NaN
장  80.0  45.0 NaN
박  60.0  73.0 NaN
강   NaN  99.0 NaN

In [414]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [415]:
df.dtypes

col1    int64
col2    int64
dtype: object

In [416]:
dates = pd.date_range("20250101", periods= 6)
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06'],
              dtype='datetime64[ns]', freq='D')

In [417]:
dates[0]

Timestamp('2025-01-01 00:00:00')

In [418]:
dates = pd.date_range("20250101", end='20250110')
dates

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05', '2025-01-06', '2025-01-07', '2025-01-08',
               '2025-01-09', '2025-01-10'],
              dtype='datetime64[ns]', freq='D')

In [419]:
dates = pd.date_range("20250101", periods= 6, freq ='3D')
dates

DatetimeIndex(['2025-01-01', '2025-01-04', '2025-01-07', '2025-01-10',
               '2025-01-13', '2025-01-16'],
              dtype='datetime64[ns]', freq='3D')

In [420]:
dates = pd.date_range("20250101", periods=6, freq='3H')
dates

/tmp/ipykernel_4141/3819429892.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  dates = pd.date_range("20250101", periods=6, freq='3H')

DatetimeIndex(['2025-01-01 00:00:00', '2025-01-01 03:00:00',
               '2025-01-01 06:00:00', '2025-01-01 09:00:00',
               '2025-01-01 12:00:00', '2025-01-01 15:00:00'],
              dtype='datetime64[ns]', freq='3h')

In [421]:
dates = pd.date_range("20250101", periods =6, freq='w')
dates

/tmp/ipykernel_4141/3726258328.py:1: FutureWarning: 'w' is deprecated and will be removed in a future version, please use 'W' instead.
  dates = pd.date_range("20250101", periods =6, freq='w')

DatetimeIndex(['2025-01-05', '2025-01-12', '2025-01-19', '2025-01-26',
               '2025-02-02', '2025-02-09'],
              dtype='datetime64[ns]', freq='W-SUN')

In [422]:
dates = pd.date_range("20260101", periods=6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [423]:
dates = pd.date_range("20260101", periods = 6, freq='W-SUN')
dates

DatetimeIndex(['2026-01-04', '2026-01-11', '2026-01-18', '2026-01-25',
               '2026-02-01', '2026-02-08'],
              dtype='datetime64[ns]', freq='W-SUN')

In [424]:
dates = pd.date_range("20260101", periods = 6, freq='w-FRI')
dates

DatetimeIndex(['2026-01-02', '2026-01-09', '2026-01-16', '2026-01-23',
               '2026-01-30', '2026-02-06'],
              dtype='datetime64[ns]', freq='W-FRI')

In [425]:
dates = pd.date_range("20250101", periods=6, freq='M')
dates

/tmp/ipykernel_4141/746379463.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range("20250101", periods=6, freq='M')

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30'],
              dtype='datetime64[ns]', freq='ME')

In [426]:
dates =pd.date_range("20250101", periods = 6, freq='MS')
dates

DatetimeIndex(['2025-01-01', '2025-02-01', '2025-03-01', '2025-04-01',
               '2025-05-01', '2025-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [427]:
dates =pd.date_range("20250302", periods=6)
dates

DatetimeIndex(['2025-03-02', '2025-03-03', '2025-03-04', '2025-03-05',
               '2025-03-06', '2025-03-07'],
              dtype='datetime64[ns]', freq='D')

In [428]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2025-03-02  0.117453 -1.374405  1.267333 -0.933989
2025-03-03  0.567079  0.323194 -1.112996 -0.489784
2025-03-04  0.184954 -1.122051 -0.156488  0.182086
2025-03-05  1.469363  0.341493  0.444937  1.091200
2025-03-06  1.038081  0.768833  0.526225 -0.069041
2025-03-07  0.076693 -1.094170 -0.585698  2.017487

In [429]:
df2 = pd.DataFrame({
    "A": 1.0,
    "B": pd.Timestamp("20260302"),
    "C": pd.Series(np.arange(1, 3, .5)),
    "D": np.array([3] * 4, dtype="int32"),
    "E":pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
})
df2

     A          B    C  D      E    F
0  1.0 2026-03-02  1.0  3   test  foo
1  1.0 2026-03-02  1.5  3  train  foo
2  1.0 2026-03-02  2.0  3   test  foo
3  1.0 2026-03-02  2.5  3  train  foo

In [430]:
df2.dtypes

A          float64
B    datetime64[s]
C          float64
D            int32
E         category
F           object
dtype: object

In [431]:
import pandas as pd

pf = pd.DataFrame(data =[[25,35, 8, 18],
                         [18, 27, 10, 20],
                         [17, 17, 10,19],
                         [12, 22, 9, 20],
                         [22, 34,8, 16]],
                  index=['윤일형','강수희', '홍소희', '유한빈', '신수빈'],
                  columns = ['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [432]:
pf['중간']

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [433]:
pf.중간

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [434]:
pf['출석']

윤일형    18
강수희    20
홍소희    19
유한빈    20
신수빈    16
Name: 출석, dtype: int64

In [435]:
pf[['출석']]

     출석
윤일형  18
강수희  20
홍소희  19
유한빈  20
신수빈  16

In [436]:
pf[['기말', '출석', '중간']]

     기말  출석  중간
윤일형  35  18  25
강수희  27  20  18
홍소희  17  19  17
유한빈  22  20  12
신수빈  34  16  22

In [437]:
pf[['기말']]

     기말
윤일형  35
강수희  27
홍소희  17
유한빈  22
신수빈  34

In [438]:
import pandas as pd
pf = pd.DataFrame(data= [[25, 35, 8, 18],
                         [18, 27, 10, 20],
                         [17, 18, 10, 19],
                         [12, 22, 9, 20],
                         [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍수희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍수희  17  18  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [439]:
pf['중간'] >20

윤일형     True
강수희    False
홍수희    False
유한빈    False
신수빈     True
Name: 중간, dtype: bool

In [440]:
pf[pf['중간'] > 20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [441]:
pf[pf['출석'] >= 19]

     중간  기말  과제  출석
강수희  18  27  10  20
홍수희  17  18  10  19
유한빈  12  22   9  20

In [442]:
pf[(pf['출석'] >= 19) & (pf['기말'] >= 20)]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [443]:
import pandas as pd
pf = pd.DataFrame(data = [[25, 35, 8, 18],
                          [18, 27, 10, 20],
                          [17, 17, 10, 19],
                          [12, 22, 9, 20],
                          [22, 34, 8, 16]],
                  index = ['윤일형', '강수희', '홍수희', '유한빈', '신수빈'],
                  columns=['중간', '기말', '과제', '출석'])

In [444]:
pf.loc['윤일형']

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [445]:
pf.loc[['윤일형']]

     중간  기말  과제  출석
윤일형  25  35   8  18

In [446]:
pf.loc[['홍수희', '윤일형']]

     중간  기말  과제  출석
홍수희  17  17  10  19
윤일형  25  35   8  18

In [447]:
pf.loc['윤일형': '유한빈']

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍수희  17  17  10  19
유한빈  12  22   9  20

In [448]:
pf.loc[pf.중간 >20]

     중간  기말  과제  출석
윤일형  25  35   8  18
신수빈  22  34   8  16

In [449]:
pf.loc[(pf.중간 > 10)& (pf.과제 == 10)]

     중간  기말  과제  출석
강수희  18  27  10  20
홍수희  17  17  10  19

In [450]:
import pandas as pd

pf = pd.DataFrame(data = [[25, 35, 8, 18],
                         [18, 27, 10, 20],
                         [17, 17, 10, 19],
                         [12, 22, 9, 20],
                         [22, 34, 8, 16]],
                  index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                  columns = ['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [451]:
pf.loc[pf.index[0]] #첫 번째 행 검색

중간    25
기말    35
과제     8
출석    18
Name: 윤일형, dtype: int64

In [452]:
pf.loc[[pf.index[0]]] #첫 번 째 행 검색

     중간  기말  과제  출석
윤일형  25  35   8  18

In [453]:
pf.loc[pf.index[1:4]] #슬라이싱 행 검색

     중간  기말  과제  출석
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20

In [454]:
pf.loc[pf.index[1:4]][['기말', '과제']]

     기말  과제
강수희  27  10
홍소희  17  10
유한빈  22   9

In [455]:
import pandas as pd
pf = pd.DataFrame(data = [[25, 35, 8, 18],
                                             [18, 27, 10, 20],
                                             [17, 17, 10, 19],
                                             [12, 22, 9, 20],
                                             [22,34, 8, 16]],
                                     index=['윤일형', '강수희', '홍소희', '유한빈', '신수빈'],
                                     columns=['중간', '기말', '과제', '출석'])
pf

     중간  기말  과제  출석
윤일형  25  35   8  18
강수희  18  27  10  20
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [456]:
pf.loc[:, '과제']

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [457]:
pf.loc[:, '중간': '과제']

     중간  기말  과제
윤일형  25  35   8
강수희  18  27  10
홍소희  17  17  10
유한빈  12  22   9
신수빈  22  34   8

In [458]:
pf.loc[:, ['기말', '출석']]

     기말  출석
윤일형  35  18
강수희  27  20
홍소희  17  19
유한빈  22  20
신수빈  34  16

In [459]:
pf.loc[:, pf.columns[0]]

윤일형    25
강수희    18
홍소희    17
유한빈    12
신수빈    22
Name: 중간, dtype: int64

In [460]:
pf.loc[:, pf.columns[1:]]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [461]:
pf.loc[:, pf.columns[1:3]]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [462]:
pf.loc[:, pf.columns[1:]][['기말', '과제']]

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9
신수빈  34   8

In [463]:
pf.loc['윤일형', '출석']

np.int64(18)

In [464]:
pf.loc['윤일형' : '유한빈', '기말']

윤일형    35
강수희    27
홍소희    17
유한빈    22
Name: 기말, dtype: int64

In [465]:
pf.loc['윤일형':'유한빈', '기말':'과제']

     기말  과제
윤일형  35   8
강수희  27  10
홍소희  17  10
유한빈  22   9

In [466]:
pf.loc[pf.index[0], pf.columns[1]]

np.int64(35)

In [467]:
pf.loc[pf.index[0:3], pf.columns[2]]

윤일형     8
강수희    10
홍소희    10
Name: 과제, dtype: int64

In [468]:
pf.loc[pf.index[0:3], pf.columns[2:]]

     과제  출석
윤일형   8  18
강수희  10  20
홍소희  10  19

In [469]:
pf.iloc[1]

중간    18
기말    27
과제    10
출석    20
Name: 강수희, dtype: int64

In [470]:
pf.iloc[[1]]

     중간  기말  과제  출석
강수희  18  27  10  20

In [471]:
pf.iloc[[1, 3]]

     중간  기말  과제  출석
강수희  18  27  10  20
유한빈  12  22   9  20

In [472]:
pf.iloc[2:]

     중간  기말  과제  출석
홍소희  17  17  10  19
유한빈  12  22   9  20
신수빈  22  34   8  16

In [473]:
pf.iloc[:, 2]

윤일형     8
강수희    10
홍소희    10
유한빈     9
신수빈     8
Name: 과제, dtype: int64

In [474]:
pf.iloc[:, [2]]

     과제
윤일형   8
강수희  10
홍소희  10
유한빈   9
신수빈   8

In [475]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [476]:
pf.iloc[1, 1]

np.int64(27)

In [477]:
pf.iloc[1:3, 1:]

     기말  과제  출석
강수희  27  10  20
홍소희  17  10  19

In [478]:
pf.iloc[:, 1:]

     기말  과제  출석
윤일형  35   8  18
강수희  27  10  20
홍소희  17  10  19
유한빈  22   9  20
신수빈  34   8  16

In [479]:
pf.iloc[[1, 3, 4], 1:]

     기말  과제  출석
강수희  27  10  20
유한빈  22   9  20
신수빈  34   8  16

In [480]:
pf.iloc[[1, 3, 4], [0,1]]

     중간  기말
강수희  18  27
유한빈  12  22
신수빈  22  34

In [481]:
pf.at['윤일형', '과제']

np.int64(8)

In [482]:
pf.at['유한빈', '기말']

np.int64(22)

In [483]:
pf.at[pf.index[1], '출석']

np.int64(20)

In [484]:
pf.at[pf.index[3], pf.columns[2]]

np.int64(9)

In [485]:
pf.iat[1, 2]

np.int64(10)

In [486]:
pf.iat[2, 3]

np.int64(19)

In [495]:
df.desc

AttributeError: 'DataFrame' object has no attribute 'desc'

In [496]:
pf.loc[:, [pf.columns[0]]] #여러 dict의 목록 데이터 사용
import pandas as pd

In [497]:
df.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [498]:
df.sum(axis=0)

사고(건)    2433
사망(명)      98
부상(명)    4899
dtype: int64

In [499]:
df.sum(axis=1)

연월
2016년1월     584
2016년2월     508
2016년3월     659
2016년4월     642
2016년5월     774
2016년6월     574
2016년7월     696
2016년8월     727
2016년9월     547
2016년10월    560
2016년11월    623
2016년12월    536
dtype: int64

In [500]:
df.cumsum(axis=0)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     366     11    715
2016년3월     583     18   1150
2016년4월     799     25   1569
2016년5월    1038     38   2091
2016년6월    1238     50   2453
2016년7월    1465     59   2913
2016년8월    1695     66   3403
2016년9월    1882     79   3750
2016년10월   2065     89   4117
2016년11월   2265     94   4535
2016년12월   2433     98   4899

In [501]:
df.cumsum(axis=1)

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192    197    584
2016년2월     174    180    508
2016년3월     217    224    659
2016년4월     216    223    642
2016년5월     239    252    774
2016년6월     200    212    574
2016년7월     227    236    696
2016년8월     230    237    727
2016년9월     187    200    547
2016년10월    183    193    560
2016년11월    200    205    623
2016년12월    168    172    536

In [502]:
df.mean()

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [503]:
df.mean(axis=0)

사고(건)    202.750000
사망(명)      8.166667
부상(명)    408.250000
dtype: float64

In [504]:
df.mean(axis=1)

연월
2016년1월     194.666667
2016년2월     169.333333
2016년3월     219.666667
2016년4월     214.000000
2016년5월     258.000000
2016년6월     191.333333
2016년7월     232.000000
2016년8월     242.333333
2016년9월     182.333333
2016년10월    186.666667
2016년11월    207.666667
2016년12월    178.666667
dtype: float64

In [505]:
df.mean(axis=None)

np.float64(206.38888888888889)

In [506]:
df.max()

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [507]:
df.max(axis=0)

사고(건)    239
사망(명)     13
부상(명)    522
dtype: int64

In [508]:
df.max(axis=1)

연월
2016년1월     387
2016년2월     328
2016년3월     435
2016년4월     419
2016년5월     522
2016년6월     362
2016년7월     460
2016년8월     490
2016년9월     347
2016년10월    367
2016년11월    418
2016년12월    364
dtype: int64

In [509]:
df.max(axis=None)

522

In [510]:
df.min()

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [511]:
df.min(axis=0)

사고(건)    168
사망(명)      4
부상(명)    328
dtype: int64

In [512]:
df.min(axis=1)

연월
2016년1월      5
2016년2월      6
2016년3월      7
2016년4월      7
2016년5월     13
2016년6월     12
2016년7월      9
2016년8월      7
2016년9월     13
2016년10월    10
2016년11월     5
2016년12월     4
dtype: int64

In [513]:
df.min(axis=None) ###########

4

In [514]:
df.describe() #수치 데이터

            사고(건)      사망(명)       부상(명)
count   12.000000  12.000000   12.000000
mean   202.750000   8.166667  408.250000
std     23.014324   3.186144   60.051682
min    168.000000   4.000000  328.000000
25%    186.000000   5.750000  363.500000
50%    200.000000   7.000000  402.500000
75%    219.500000  10.500000  441.250000
max    239.000000  13.000000  522.000000

In [515]:
df.iloc[:, 1:].sum(axis=1)

연월
2016년1월     392
2016년2월     334
2016년3월     442
2016년4월     426
2016년5월     535
2016년6월     374
2016년7월     469
2016년8월     497
2016년9월     360
2016년10월    377
2016년11월    423
2016년12월    368
dtype: int64

In [516]:
df2.sum()

사고(건)    2433
사망(명)      98
부상(명)    4899
재해자수     4997
dtype: int64

In [517]:
df2.loc['총계'] = df2.sum(axis=0)
df2

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192      5    387   392
2016년2월     174      6    328   334
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년6월     200     12    362   374
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년9월     187     13    347   360
2016년10월    183     10    367   377
2016년11월    200      5    418   423
2016년12월    168      4    364   368
총계         2433     98   4899  4997

In [518]:
df2>10

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    True  False   True  True
2016년2월    True  False   True  True
2016년3월    True  False   True  True
2016년4월    True  False   True  True
2016년5월    True   True   True  True
2016년6월    True   True   True  True
2016년7월    True  False   True  True
2016년8월    True  False   True  True
2016년9월    True   True   True  True
2016년10월   True  False   True  True
2016년11월   True  False   True  True
2016년12월   True  False   True  True
총계         True   True   True  True

In [519]:
df2[df2>10]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월     192    NaN    387   392
2016년2월     174    NaN    328   334
2016년3월     217    NaN    435   442
2016년4월     216    NaN    419   426
2016년5월     239   13.0    522   535
2016년6월     200   12.0    362   374
2016년7월     227    NaN    460   469
2016년8월     230    NaN    490   497
2016년9월     187   13.0    347   360
2016년10월    183    NaN    367   377
2016년11월    200    NaN    418   423
2016년12월    168    NaN    364   368
총계         2433   98.0   4899  4997

In [520]:
df2[[True] *6 + [False]*7]

         사고(건)  사망(명)  부상(명)  재해자수
연월
2016년1월    192      5    387   392
2016년2월    174      6    328   334
2016년3월    217      7    435   442
2016년4월    216      7    419   426
2016년5월    239     13    522   535
2016년6월    200     12    362   374

In [521]:
df2 ['재해자수'] >400

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월      True
2016년6월     False
2016년7월      True
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월     True
2016년12월    False
총계           True
Name: 재해자수, dtype: bool

In [522]:
df2[df2['재해자수'] > 400]

          사고(건)  사망(명)  부상(명)  재해자수
연월
2016년3월     217      7    435   442
2016년4월     216      7    419   426
2016년5월     239     13    522   535
2016년7월     227      9    460   469
2016년8월     230      7    490   497
2016년11월    200      5    418   423
총계         2433     98   4899  4997

In [524]:
df['사망(명)'] == 7

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [525]:
df['사망(명)'].isin([7])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월    False
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [526]:
df['사망(명)'].isin([7, 10])

연월
2016년1월     False
2016년2월     False
2016년3월      True
2016년4월      True
2016년5월     False
2016년6월     False
2016년7월     False
2016년8월      True
2016년9월     False
2016년10월     True
2016년11월    False
2016년12월    False
Name: 사망(명), dtype: bool

In [527]:
df[df['사망(명)'].isin([7, 10])]

          사고(건)  사망(명)  부상(명)
연월
2016년3월     217      7    435
2016년4월     216      7    419
2016년8월     230      7    490
2016년10월    183     10    367

In [528]:
df[ (df['사망(명)'].isin([7, 10])) | (df['부상(명)'] > 350)]

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [529]:
df[df.index.str.contains('3')]

         사고(건)  사망(명)  부상(명)
연월
2016년3월    217      7    435

In [531]:
df3 = df.copy()
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월     192      5    387
2016년2월     174      6    328
2016년3월     217      7    435
2016년4월     216      7    419
2016년5월     239     13    522
2016년6월     200     12    362
2016년7월     227      9    460
2016년8월     230      7    490
2016년9월     187     13    347
2016년10월    183     10    367
2016년11월    200      5    418
2016년12월    168      4    364

In [532]:
df3[df3> 10] = -df3
df3

          사고(건)  사망(명)  부상(명)
연월
2016년1월    -192      5   -387
2016년2월    -174      6   -328
2016년3월    -217      7   -435
2016년4월    -216      7   -419
2016년5월    -239    -13   -522
2016년6월    -200    -12   -362
2016년7월    -227      9   -460
2016년8월    -230      7   -490
2016년9월    -187    -13   -347
2016년10월   -183     10   -367
2016년11월   -200      5   -418
2016년12월   -168      4   -364

In [536]:
df = pd.DataFrame({'A':range(1, 6),
                   'B': range(6, -3, -2),
                   'C': range(10, 5, -1),
                   'D clmns':range(3, -2, -1),
                   'E': ['python', 'java', 'python', 'go', 'python']})
df

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [537]:
df.query('A > B')

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [538]:
df[df.A > df. B]

   A  B  C  D clmns       E
2  3  2  8        1  python
3  4  0  7        0      go
4  5 -2  6       -1  python

In [540]:
df.query('C== 10')

   A  B   C  D clmns       E
0  1  6  10        3  python

In [541]:
df.query('A>0')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [542]:
df.query('E == "python"')

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [543]:
df.query("E != 'python'")

   A  B  C  D clmns     E
1  2  4  9        2  java
3  4  0  7        0    go

In [544]:
df.query('A == `D clmns`')

   A  B  C  D clmns     E
1  2  4  9        2  java

In [545]:
df.query('A == "D clmns"')

Empty DataFrame
Columns: [A, B, C, D clmns, E]
Index: []

In [546]:
df[df.A == df["D clmns"]]

   A  B  C  D clmns     E
1  2  4  9        2  java

In [547]:
df.query('A > 3| B > 8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [548]:
df.query('A > 2 & C <8')

   A  B  C  D clmns       E
3  4  0  7        0      go
4  5 -2  6       -1  python

In [549]:
df.query("E in ['python', 'go']")

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
3  4  0   7        0      go
4  5 -2   6       -1  python

In [550]:
num = 3
df.query('B > @num')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [551]:
num = 3
df.query(f'B > {num}')

   A  B   C  D clmns       E
0  1  6  10        3  python
1  2  4   9        2    java

In [552]:
s = "E.str.contains('py')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python

In [553]:
s = 'E.str.startswith("g")'
df.query(s)

   A  B  C  D clmns   E
3  4  0  7        0  go

In [554]:
s = "E.str.endswith('on')"
df.query(s)

   A  B   C  D clmns       E
0  1  6  10        3  python
2  3  2   8        1  python
4  5 -2   6       -1  python